# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "trusty64"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |box|
      box.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision "docker" do |d|
    d.run "hopsoft/graphite-statsd",
      args: "-d \
            --name graphite \
            -p 80:80 \
            -p 2003:2003 \
            -p 8125:8125/udp"
            
    d.run "dockerfile/mongodb",
      cmd: "mongod"
      args: "-d \
            --name mongodb \
            -p 27017:27017"
  end

  config.vm.provision "docker",
    images: ["hopsoft/graphite-statsd"]

  config.vm.provision "shell", path: "install-tank.sh"

end
